### ISSUE TITLE
javaagent  collector  port 4318

### ISSUE THREAD

**Issue by systems1** [open-telemetry/opentelemetry-java-examples#367]
past java example code here in examples  had   collector  default port 4317 
im using collector-contrib and can get metrics traces (4317) but not logs
using logback-spring.xml 

4317 is grpc 
4318 is http 

if logs cannot be exported over 4317 ? as its changed from past example javaagent 4317  to 4318 
if my config is updated from 4317 to 4318 ,all traces metrics logs are failing to  connect collector at http://collector:4318 

otel.conf
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

logback-spring.xml

```xml
  <springProfile name="dev, staging, prod">
    <appender name="otlp-collector" class="ch.qos.logback.classic.net.SocketAppender">
      <remoteHost>collector</remoteHost>
      <port>4318</port>
    </appender>
  </springProfile>
```

[otel.javaagent 2024-03-27 14:44:38:498 +0000] [OkHttp http://collector:4318/...] WARN io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export spans. Server responded with gRPC status code 2. Error message: FRAME_SIZE_ERROR: 4740180

	[otel.javaagent 2024-03-27 14:44:16:406 +0000] [OkHttp http://collector:4318/...] WARN io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export metrics. Server responded with gRPC status code 2. Error message: FRAME_SIZE_ERROR: 4740180

[otel.javaagent 2024-03-27 14:39:46:727 +0000] [OkHttp http://collector:4318/...] WARN io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export spans. Server responded with gRPC status code 2. Error message: 

message:[otel.javaagent 2024-03-27 14:51:16:426 +0000] [OkHttp http://collector:4318/...] WARN io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export metrics. Server responded with gRPC status code 2. Error message: Broken pipe logStream:b0b76c317d85aa312d6779fd4a3db399f009c5b6e1512f8be0dc6dbf639c0df5 @timestamp:Mar 27, 2024 @ 09:51:16.427 @version:1 id:38168864449669339858687673274219390502717780978530844672

io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export metrics. Server responded with gRPC status code 2. Error message: Connection reset by peer

**Comment by jaydeluca** [comment]
do you have a logging pipeline configured in your collector config?

For example:

```
service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, zipkin, otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]
    logs:  <---- this block
      receivers: [otlp]
      processors: [ batch ]
      exporters: [ logging ]
```
